#!/usr/bin/env sh

while true; do
  if [ $[RANDOM % 2] -eq 0 ]; then
    tput bold
  else
    tput sgr0
  fi
  if [ $[RANDOM % 5] -eq 0 ]; then
    tput setaf 1
  else
    tput setaf 7
  fi
  cat /dev/urandom | head -1
done
